mvt/encode.go, mvt/encode_test.go, wkb/line_string.go, wkb/line_string_test.go, wkb/point.go, wkb/point_test.go, wkb/wkb.go, wkb/wkb_test.go
Built the Point and Line String decode geometeries.
Added basic geometery interface.
closes #1
closes #2
=> Built out Point and Line String

provider/postgis/postgis.go
Issue #66 was because due to postgres keywords were conflicting with the table and column names. Just need to quote the names.
Add ENV to control sql debug output.
Now you can use the SQL_DEBUG environmental variable to specify the type of debug information you want to see. Currently support two values.
1. LAYER_SQL - this will show you the layer sql as they are parse or generated from the config files.
2. EXCUTE_SQL - will show you the actual sql that is getting executed for each call, and the number of items it returns or if it errored.
Fixes #66
=> Fixes Issues #66

README.md, mvt/layer.go, mvt/layer_test.go
@ARolek Can you do a quick review for this pull request. Quick temp fix for #102.
=> Quickfix for #102

server/handle_capabilities.go, server/handle_map_capabilities.go, server/server.go
No tests, as I couldn't figure out how to include HTTP headers in the existing test cases.
Fixes #135
=> X-Forwarded-Proto support

.travis.yml, maths/makevalid/plyg/ring.go, maths/webmercator/pseudo.go, provider/postgis/postgis.go, provider/postgis/postgis_foreach.go
Issue #156 reported squashing of types in the Y direction. This was
due to a multiplication changing to a plus.
Fixes #156
=> [issue-156] Fix #156 for regression of dealing with WGS84

internal/log/README.md, internal/log/log.go, internal/log/log_test.go, internal/log/standard.go, internal/log/stdLogger.go
=> Log proxy w/ std logger implementation & tests.

server/handle_map_layer_zxy.go, server/handle_map_layer_zxy_test.go, server/handle_map_zxy.go, server/handle_map_zxy_test.go
Resolves issue #229 & prevents similar issue with x value.
=> Updated server to check that x & y values for tiles are positive. (#229)

.travis.yml, docker/Dockerfile
I'd like to temporarily merge these three commits into master and add a tag to ensure that everything is working as expected.  Once we've ensured it's working, the release, tag, and these three commits will be deleted (They'll be sure to work as part of v0.6.0 when it's ready).
=> Issue 244 dockerfile master

.travis.yml, docker/Dockerfile
1. Update docker comments in Dockerfile & .travis.yml.
1. Update .travis.yml to push an image to gospatial/tegola:latest in addition to gospatial/tegola:<version>.
=> Update Dockerfile documentation - #257

provider/provider.go
@gdey and I landed on this design for the provider interface overhaul. @JivanAmara let me know any questions you have.
=> new provider interface to ulitmately replace MVTProvider(). #182

atlas/map.go, geom/encoding/wkt/internal/cmd/fuzz/README.md, geom/encoding/wkt/internal/cmd/fuzz/fuzz/fuzz.go, geom/encoding/wkt/internal/cmd/fuzz/main.go, geom/encoding/wkt/wkt.go, geom/encoding/wkt/wkt_test.go, geom/geom.go
Fixed issue #291 where wkt encoder will panic for nil or zero value geometries.
=> Issue 291 wkt nil

geom/bbox.go, geom/bbox_test.go
In prepration to merge all the bounding box implementation we have in
the code, augementing the geom bbox with the functions that others are
relying on.
=> Added accessor function to bbox #270

geom/encoding/geojson/geojson.go, geom/encoding/geojson/geojson_internal_test.go, geom/encoding/geojson/geojson_test.go, geom/polygon.go
- close polygon (and multi polygon) rings during MarshalJSON calls
to match GeoJSON spec.
=> close polygon rings for geojson #327

cmd/tegola/cmd/root.go, config/config.go, config/config_test.go, util/dict/gen.pl, util/dict/map.go, util/dict/map_test.go
This may also close #360 
Include some changes to the map.go file and it's internals for compatibility with pointers to their underlying values.
=> Issue 354 default values for min/max zoom in layers config

provider/gpkg/gpkg.go, provider/postgis/postgis_test.go, provider/postgis/util.go, provider/postgis/util_internal_test.go, server/handle_map_layer_zxy.go
Additional test cases and minor code formatting changes to #478
=> Olt postgis sub queries

provider/postgis/util.go, provider/postgis/util_internal_test.go
uppercaseTokens fails if the query contains exclamation marks (e.g. bar != 42).
I replaced it with a regexp that only matches tokens like `!Tok-EnS_01!`.
=> provider/postgis: fix uppercaseToken for queries with != etc.

.travis.yml, ci/config_postgis.sh, provider/postgis/README.md, provider/postgis/postgis.go, provider/postgis/postgis_internal_test.go
- adds error checking on result sets of rows
- closes #538
=> better error checking for provider/postgis

cmd/tegola/cmd/root.go, cmd/tegola/cmd/server.go
Add tegola serve [-n, --no-cache] flag. It overrides config cache section.
=> Add support for --no-cache override

atlas/map.go, cmd/internal/register/maps.go, cmd/tegola/cmd/server.go, cmd/tegola_lambda/main.go, config/config.go, config/config_test.go, server/handle_map_layer_zxy.go, server/handle_map_layer_zxy_test.go, server/handle_map_style_internal_test.go, server/server.go
* server: replace TileBuffer with TileBuffers,
* config: add per-map tile_buffer configuration
* cmd: use config.TileBuffersMap() for server.TileBuffers
=> Add per-map tile_buffer configuration

README.md, atlas/layer.go, atlas/map.go, cmd/internal/register/maps.go, cmd/xyz2svg/cmd/draw.go, config/config.go, config/config_test.go, maths/validate/validate.go, mvt/feature.go, mvt/feature_internal_test.go, mvt/layer.go
This branch implements the code review suggestions
for the PR submitted by paumas to implement the
dont_clip map configuration.
=> Paumas implement dont clip flag

cache/redis/README.md, cache/redis/redis.go
=> cache/redis: add configurable key expiration time #600

server/middleware_gzip.go
- Corrected Content-Length
- also skipping the unnecessary buffer
=> Content-Length for non-gzipped responses

server/handle_map_layer_zxy.go, server/handle_map_layer_zxy_test.go, server/server_test.go
=> server: return tiles that lie on a Map's boundary

ci/build_binary.sh
* added tegola_lambda_cgo to the build pipeline so geopackage
can be used.
* bumped the xgo build version of Go to 1.12
=> Added tegola_lambda_cgo to the build pipeline

atlas/cache_azblob.go, atlas/cache_redis.go, atlas/cache_s3.go, atlas/provider_gpkg.go, atlas/provider_postgis.go, cmd/tegola/pprof.go
=> fix: typo direcotry -> directory

cmd/tegola/cmd/cache/seed_purge.go
To ease review process of #655, I separate this lint error.
=> lint: fix error ending with .

atlas/map.go, cmd/internal/register/maps.go, config/config.go, provider/errors.go, provider/postgis/postgis.go, provider/postgis/util.go, provider/provider.go
Cleanup and refactored DataProvider interface to support
adding differet types of data providers. This is to keep this
branch alined with tegola-postgis
=> Refactored DataProvider Interface

.github/workflows/on_pr_push.yml, README.md, atlas/map.go, cmd/internal/register/errors.go, cmd/internal/register/maps.go, cmd/internal/register/maps_test.go, cmd/internal/register/mvt_providers.go, cmd/tegola/cmd/root.go, cmd/tegola_lambda/main.go, config/config.go, config/config_test.go, config/errors.go, mvtprovider/layer.go, mvtprovider/postgis/README.md, mvtprovider/postgis/doc.go, mvtprovider/provider.go, provider/errors.go, provider/postgis/debug.go, provider/postgis/error.go, provider/postgis/postgis.go, provider/postgis/postgis_internal_test.go, provider/postgis/postgis_test.go, provider/postgis/register.go, provider/postgis/util.go, provider/postgis/util_internal_test.go, provider/provider.go, ui/package-lock.json, ui/package.json
This brings in the mvt_providers features.
=> Migrate mvt providers

cmd/tegola/cmd/cache/worker.go
Check if no layers exist for a map after filtering layers by zoom.
closes #698
=> Fixed cache seed zoom filter handling

.github/CODEOWNERS
Updated codeowners so that pr are tagged correctly for reviewers
=> Added mapl and arolek to codeowners for ui

mvtprovider/postgis/README.md
When working with data in 4326 projection and leveraging
PostGIS' ST_AsMVTGeom function the geometries and !BBOX! need
to be reprojected prior to passing to ST_AsMVTGeom.
close #731
=> Updated mvt_postgis README regarding 4326 projection

ui/package-lock.json, ui/package.json, ui/src/App.vue
Updating npm packages that have critical vulnerabilities.
=> UI deps updates

provider/gpkg/gpkg.go, provider/gpkg/gpkg_register.go
closes #805
I also added support for floating point tag columns (I came across this in the natural earth dataset)
=> gpkg: improve error messages in registration

cache/redis/README.md
minor addition to the redis docs that were missing from the initial PR
=> docs: update

.github/workflows/on_release_publish.yml
Fixes #945
Adding `context: .` fixes issue with missing files. I've pushed image to my own [repository](https://hub.docker.com/r/manastyretskyi/tegola) so that you would be able test it as well.
=> Fix docker image viewer UI

Dockerfile, go.mod
Bumping Go to address govulncheck errors.
=> Bump Go to 1.24.2
