go-spatial/tegola

provider/postgis/postgis.go

In the layers configuration for the postgis provider many of the tablenames are the same as the layer name, this removes the duplication.

[feature] Make tablename default to layername

---

README.md
basic/line.go
basic/polygon.go
mvt/feature.go
mvt/feature_test.go
mvt/tile.go
provider/postgis/postgis.go
server/handle_map_capabilities.go
wkb/collection.go

Additionally, several misspellings of 'geometery' -> 'geometry'.

Fix misspellings reported in #105.

---

server/handle_map_layer_zxy.go
server/handle_map_layer_zxy_test.go
server/handle_map_zxy.go
server/handle_map_zxy_test.go

Zoom value is now check to see if it's greater then or equal to zero.
If it isn't log that we got a bad value and return a 400 error.

[issue-163] If the z value is neg return a bad request.

---

README.md

This throws an error as is.
```
2017/12/21 10:16:01 root.go:77: max_connections value needs to be of type int64. Value is of type string
```

max_connections value needs to be of type int64.

---

wkb/wkt.go

When writing out WKT's of a geometry collection we were using the index,
instead of the geometry.
Fix #227

[issue-227] Quick fix for bug reported in #227

---

LICENSE.md
internal/log/README.md
internal/log/log.go
internal/log/log_test.go
internal/log/standard.go

Go code regularly uses calls like
```
f, err := os.Open("filename.ext")
if err != nil {
log.Fatal(err)
}
```
This updates the logger to accept an error var in addition to a string.

Logging interface now has formatting and raw log methods, i.e. Errorf() / Error()

---

server/middleware_tile_cache.go
server/middleware_tile_cache_internal_test.go

The tile cache middleware was writing to the cache on any response. This patch checks for http 200 status codes before writing to the cache.

Issue 250 - tile cache response writer - catch non 200 response

---

.travis.yml
docker/Dockerfile

Adds a Dockerfile for building a binary and creating a minimal deployment image using the alpine docker image as a base.
Using static linking, cgo support is included, entirely encapsulated in the binary with trivial difference to binary size.  Since it isn't affecting dependencies or binary/image size I think we should reconsider separating pure go & cgo-support docker images.

Issue 244 - Dockerfile

---

mvt/feature.go
mvt/feature_test.go

A check that if a line had only 1 or fewer points was
check if a line had 2 or few points to disgard. This
will no longer happen.
fixed #280

[issue-280] 2pt lines were being disgarded.

---

atlas/map.go
maths/clip/clip.go
maths/clip/linestring_test.go

Fixes #290 range panic.
#290 identifies a panic in the clipping of a linestring.

Issue 290 panic idx out of range

---

server/handle_map_style.go
server/server.go

- don't include auto generated style when
the geometry type for a layer can't be infered
- migrating log statements for server package to
internal logger

style generator fix for nil geoms. #302

---

atlas/layer.go
atlas/map.go
cmd/tegola/cmd/root.go
config/config.go
config/config_test.go

- plubmed through layer simplification control to the tegola config
- updated config Parse and Validate tests to use new format
- removed log_format and log_file config artifacts (#255)

configurable layer simplification #165

---

maths/makevalid/makevalid.go
maths/makevalid/makevalid_test.go
maths/points/sorted.go
maths/points/sorted_test.go

previously, the "find unique" part of these functions would shift everything down when it found unique value(s). This has a worst case runtime of O(n^2). New approach shifts down as you go, O(n). 
While this will probably have little impact on real world performance I found the old version difficult to follow with the 2 extra if conditions.
benchmarks are with 400ish floats, the sort is included as part of the benchmarks:
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkSortUniqueF64-4               16916         15703         -7.17%
BenchmarkSortUniqueF64_worstCase-4     20154         14002         -30.52%
```

simplify sort+unique functions

---

cache/file/README.md
cache/redis/README.md

A few cleanups for the cache types documentation.

Typo, grammar, clarity fixes.

---

geom/encoding/wkb/internal/decode/decode.go

One of the errors detected by fuzzing (#53, #384) was the creation of valid geometries from corrupt data. This patch goes some ways to remedying this by checking if the BOM is correctly set (0 or 1) as per the specification and returning an error if it is any other value.

wkb/encoding package: check if Byte Order Marker is correctly set before processing stream

---

cache/s3/s3.go

Support for non AWS endpoints, based on this example https://www.digitalocean.com/community/questions/how-to-use-digitalocean-spaces-with-the-aws-s3-sdks?answer=39593
This is the first time I've written in Go, so please let me know if I made a mistake

#413 add support for non AWS S3 endpoints

---

cache/file/file.go
cache/file/file_test.go

Issue 435 & 422: filecache: on Windows files are written with invalid names

---

internal/env/dict.go
internal/env/dict_test.go

For my explanation, the letter "T" represents all types ("string", "bool", "int", etc.)
The error was a result of passing the `[]interface{}` into `ParseT()` vs a single element from the `[]interface{}`. Also added tests for converting from `[]interface{}`to `[]T` and `interface{}` to `T`

Issue 445 env package not properly parsing slices

---

provider/postgis/README.md
provider/postgis/postgis.go

Replacing both variations to !BBOX! on init, to avoid conversion for each request.
Closes #443

postgis: add support for !bbox! (Mapnik) and !BOX! (MapServer) tokens

---

server/README.md

This fixes the spelling of "Server" within the level 1 heading.
This will close issue #475.

Fix "Server" heading spelling

---

README.md
provider/postgis/postgis.go
provider/postgis/postgis_internal_test.go

addressed in #180 
This feature is important for more complex queries (joins or spatial operations) were a `LIMIT 1` still has to run against the whole table (because !BBOX! covers the whole planet).

provider/postgis: add geometry_type option to avoid table inspection

---

README.md
cmd/tegola/pprof.go

Allow to use Go's pprof profiler.
This should have no measurable impact when not enabled via ``TEGOLA_HTTP_PPROF``, but I did not found any reliable source for that.
I added a build flag anyway, but can remove it or flip the default (i.e. make it `+build pprof`).

enable Go pprof profiler with TEGOLA_HTTP_PPROF environment

---

cache/s3/README.md
cache/s3/s3.go

added support for MIME type in S3 caches #459

Issue 459 mime type

---

provider/gpkg/gpkg_register.go
provider/postgis/postgis.go
server/server.go

- added Cleanup routine to postgis to explicitly close the connection pool on shutdown.
- better error management for http server.ListenAndServe

provider/postgis - close connection pool

---

mvt/cleanline_internal_test.go
mvt/feature_internal_test.go
mvt/fuzz.go
mvt/layer.go
mvt/layer_internal_test.go
mvt/layer_test.go
mvt/mvt.go
mvt/tile.go
provider/postgis/postgis.go
provider/postgis/util.go

- removed the unique ID check to match the mvt spec
which says IDs SHOULD be unique but is not a MUST.
- reworked mvt tests to closer align to the new testing
structure and remove the dependency on tbltest package

don't require IDs for mvt features. closes #338

---

cmd/tegola/cmd/cache/seed_purge.go

when the --map flag is used the map was set twice as the
seedPurgeCmdValidatePersistent method is called twice.
this commit makes the method idempotent but does not address
the double call.
closes #553

Double seeding of cache when using tile-list

---

maths/line_intersect.go

I think we don't need sort.Ints in FindIntersectsWithEventQueueWithoutIntersect function.
It makes decrease 30%-50%  time to render tiles for me.

make better performance by Remove not needed sort

---

config/config.go
config/config_test.go

Addressed issue where map tile buffers were not being set correctly
for configured maps 2+. This was due to a return statement when
a continue should have been used. Updated test cases accordingly.

Fixed tile buffer not being set correctly #573

---

provider/postgis/error.go
provider/postgis/postgis.go
provider/postgis/postgis_test.go
provider/postgis/util.go

Added a check to the result set field descripters of TileFeatures
to ensure the configured geom_fieldname is present. This catches
a misconfiguration error that may arise at runtime.
closes #590

provider/postgis: no error thrown when geoFieldname is missing

---

cmd/tegola/cmd/server.go
cmd/tegola_lambda/main.go
server/middleware_headers.go
server/middleware_headers_test.go
server/middleware_tile_cache.go
server/server.go
server/server_cors_test.go

* Fixed bug where user defined headers were not being added
to OPTIONS requests.
* Added associated tests.
closes #594

Custom webserver headers are not added to OPTIONS requests

---

README.md

* Added a footnote about go versions and which versions
are used to build tegola.

[DOC] Updated readme with footnote about build

---

cache/s3/s3_test.go

Travis breaks tests on pull requests because it is unable to decrypt
the creds for S3. We should really skip these test, and not fail.

[ci] Currently Travis breaks because of S3

---

cmd/tegola/cmd/root.go

I changed the `rootCmdValidatePersistent` function to check command names and skip the config init function. Now, `version` and `help` can be run cleanly without a config file.

skip initialization of config in version and help commands

---

atlas/atlas.go
atlas/map.go
example/tile.go
mvt/debug.go
mvt/feature.go
mvt/feature_internal_test.go
mvt/layer.go
mvt/layer_internal_test.go
mvt/layer_test.go
mvt/scale.go
mvt/scale_internal_test.go
mvt/tile.go

The mvt encoding package contained core geo processing routines
(i.e. simplification, make valid, scaling). These routines have
been carved out of the mvt pacakge and moved into the atlas
map Encode() step. This allows the mvt package to focus entirely
on encoding.
This is a transitional step which positions tegola to adopt the
new make valid routine which is currently under development in the
geom package. This transition also positions tegola to adopt the
new simplification routine which is in the geom package. The mvt
package will soon be carved out of tegola and also moved to the
geom package.
During the refactor, a fair amount of code was purged from the mvt
package and many function signatures were able to reduce the number
of parameters they required. Additionally the mvt feature …

Move geometry processing out of mvt package

---

atlas/map.go
mvt/debug.go
mvt/feature.go
mvt/feature_internal_test.go
mvt/layer_internal_test.go
mvt/layer_test.go
mvt/scale.go
mvt/scale_internal_test.go

See more on #628 
There is a file, `mvt/debug.go` that still uses `basic` types, I'm not sure if it should be kept; please advise.

remove basic types from mvt package

---

cmd/tegola/cmd/server.go
cmd/tegola_lambda/main.go
config/config.go
config/errors.go
server/README.md
server/handle_capabilities.go
server/handle_capabilities_test.go
server/handle_map_capabilities.go
server/server.go
server/server_internal_test.go
server/server_test.go

Added the webserver config property uri_prefix which allows for
setting an API route prefix. This is commonly used when tegola
is run behind a reverse proxy (i.e. example.com/tegola). Certain
routes (i.e. capabilities) build URLs which are included in the
response and then passed back to the proxy. Without the ability
to set a URI prefix, the URLs in the capabilities responses
will not be useable by the consuming client.
Setting the webserver hostname now ignores the server port. It's
assumed that if the user is setting the hostname they want full
control of it.
closes #136

Added configurable webserver URI Prefix to

---

atlas/map_test.go
ci/build_nonrelease.sh
ci/go_test_multi_package_coverprofile.sh

Since bb663be505dfab59c178595d5a5688f9650d1f7f geom is not vendored so we need to `go get` in order to get tests running.

ci: install geom package in ci build

---

.travis.yml

Simple upgrade to latest go version.
I plan to work on #520 (I hope to be able to use the mbtile "offline" later) and maybe others issues somewhat related #602 #583. But before, I would suggest this unrelated change. 😄

ci: upgrade to go1.13

---

cmd/tegola/cmd/cache/cache.go

During #655, this command line check seems to fail to check lat lng validity by validating every float.

fix: wrong cli check

---

provider/postgis/README.md
provider/postgis/postgis.go
provider/postgis/postgis_test.go
provider/postgis/util.go

should close #383 
The sql generator always adds a `gid` field, if config also includes the `gid` field as a tag, it is added twice. Meaning there could be two identical `gid` columns. The `decipherFields` function, also parses the first appearance of `gid` as usual but the second as a tag.

Issue 383 - Id field as tag

---

maths/triangle.go

This fixes a dropped error variable in the `maths` package.

maths: fix dropped error

---

provider/postgis/postgis.go
provider/postgis/util.go

This fixes two dropped `err` variables in `provider/postgis`.

provider/postgis: fix dropped errors

---

maths/webmercator/pseudo.go

This fixes the check on `PLonToX()` to truly check if `lon` is `NaN`.

maths/webmercator: fix no-op NaN check

---

server/handle_map_layer_zxy_test.go

This fixes a dropped test error in the `server` package.
Some `gofmt` changes happened automatically in my editor, and they came along for the ride.

server: fix dropped test error

---

provider/postgis/postgis.go

We only support 2D geometries at current. When ignoring such geometries we will log that the geometry has been ignored, and give a useful workaround using ST_Force2D().
Fixes #449

When ignoring UnknownGeometryType log the issue.

---

provider/postgis/util_internal_test.go

This changes a spot in `provider/postgis` where a deferred `Close` to a database query was happening before the `err` check.

provider/postgis: close query after err check

---

cache/s3/s3.go

This replaces the deprecated `session.New()`.
`go doc github.com/aws/aws-sdk-go/aws/session.New`
>Deprecated: Use NewSession functions to create sessions instead. NewSession has the same functionality as New except an error can be returned when the func is called instead of waiting to receive an error until a request is made.

cache/s3: replace deprecated S3 function

---

.github/workflows/on_release_publish.yml
Dockerfile

* Bump Go to 1.5.6
* Bump alpine linux to 3.12
* Bump musl-dev to 1.1.24r10
* Bump gcc to 9.3.0-r2
* Fixed Go linker change that happened in Go 1.15

Version bumps in Dockerfile

---

.github/workflows/on_release_publish.yml

Compiling MacOS release builds on Linux — as the GitHub Actions CI job does now — means cgo isn't enabled, which means the go-sqlite3 package isn't compiled, which means no GeoPackage support in the MacOS builds.
This pull request separates the jobs so that Linux builds are compiled on the `ubuntu-latest` runner while MacOS builds are compiled on the `macos-latest` runner. This means no cross-compilation is required and cgo can run happily.
Resolves go-spatial/tegola#736

Separate Linux and MacOS CI release build jobs

---

observability/prometheus/cache.go

The errors counter was not initialized, and was causing a panic.
Not sure how to replicate issue in a test case; so no test case for
now. Will continue to think on this.

[bug] Fix panic on using Prometheus Cache metrics.

---

atlas/atlas.go
atlas/layer.go
atlas/map.go
internal/observer/null.go
observability/observability.go
observability/prometheus/README.md
observability/prometheus/cache.go
observability/prometheus/prometheus.go
provider/postgis/postgis.go
provider/postgis/util.go
server/handle_map_layer_zxy.go

* Observability of the postgis pool
* MVTProvider has query time observability on a per map and zoom level
* Provider has query time observability on a per map, per layer and zoom level

[dataprovider] Added Observability to postgis data provider

---

server/viewer.go

When serving up static files we need to strip any proxy prefixes we may add onto the URL.
We forgot to check to see if the prefix had a "/" at the end of it, and if it did made sure
to strip it out, as static files should always start with a "/". However, if we did not remove
the "/" at the end of the prefix that we then use to trim the url; we would end up trimming off
the starting "/". This fixes that.
Fixes #735

Make sure to strip "/" for static files if URIPrefix ends with a "/"

---

.github/actions/amazon-linux-build-action/Dockerfile
.github/actions/amazon-linux-build-action/action.yml
.github/actions/amazon-linux-build-action/entrypoint.sh
.github/workflows/on_pr_push.yml
.github/workflows/on_release_publish.yml

AWS Lambda uses Amazon Linux for Lambda executions. The previous
build pipeline was using Ubuntu 18.04 to build tegola_lambda
which had GLIB location parity with Amazon Linux. After upgrading
to Ubuntu 20.04 the GLIB references between Ubuntu and Amazon Linux
are no longer in parity so tegola_lambda fails to find GLIB during
Lambda execution.
This commit accomplished the following:
* build tegola_lambda using Amazon Linux rather than Ubuntu
* move from using ubuntu-latest to ubuntu-20.04 in GH actions.
closes #789

Refactor tegola_lambda CI to use Amazon Linux for building

---

cmd/internal/register/maps.go
cmd/internal/register/maps_test.go

Issue #798
Allow link in attribution by unescape anchor tag.

Allow link in attribution

---

cmd/tegola/cmd/root.go
config/config.go

This feature is helpful for running configs generated from another command (like `dhall-toml` 👀).
The `-` is an idiomatic alias for stdin used in commands like `curl` and `grep`.

config: read config from stdin

---

cache/redis/errors.go
cache/redis/redis.go
cache/redis/redis_test.go

As discussed in #815 I create a new option for redis. I follow your implementation to the point where I check if `ssl` is true. If it's the case I split the `addr` into host and port and create a `tls.Config`. I follow [`ParseURL`](https://github.com/go-redis/redis/blob/16ab0f2ac309166bfef5cde51742f84c61c1e73c/options.go#L211) implementation here and add a TLSConfig to the `redis.Options`.

feat: redis ssl in cache options

---

.github/workflows/on_release_publish.yml

Previously binaries were only built on push so pull requests from
oustside contributors were not building binaires.

Build binaries on pull requests

---

.github/workflows/on_release_publish.yml

Whenever something is pushed to Tegola default branch, publish an 0day/edge image.

ci: publish edge image on push or pr to default_branch_ref

---

.github/workflows/on_release_publish.yml

The gen_version job is missing the code checkout. Therefor getting the default branch errors out with
```
fatal: not a git repository (or any of the parent directories): .git
```

fix: gen_version job missing checkout action

---

cache/s3/README.md

Update S3 cache properties documentation

---

atlas/atlas.go
atlas/map.go
cmd/tegola_lambda/main.go
internal/log/log.go
observability/observability.go
observability/prometheus/prometheus.go
provider/postgis/postgis.go
provider/postgis/util.go
server/handle_map_capabilities.go

As discussed I switched to the internal logger and changed current print statements to their respective log level to the best of my knowledge. Also as discussed I did not touch the math package.

chore: switch to internal/log

---

server/handle_map_layer_zxy.go

As discussed I'm removing the `logAndError` helper and let control logging for those three occasions in the error block. If you disagree with me on the `Debug` instead of the `Info` log, please feel free to just change it around. :)

chore: remove logAndError

---

docker-compose.yml
provider/postgis/util_internal_test.go

This PR adds a local development environment using [docker compose](https://docs.docker.com/compose/) as proposed [here](https://gophers.slack.com/archives/C9LA1F8F8/p1646922370441369) that makes local development a breeze, even if you're unfamiliar with the project.
1. clone the repository
2. `docker compose up`
3. run test suite
```
RUN_POSTGIS_TESTS=yes RUN_REDIS_TESTS=yes PGSSLMODE=disable PGSSLKEY="" PGSSLCERT="" PGSSLROOTCERT="" PGHOST=localhost PGPORT=5432 PGDATABASE=tegola PGUSER=postgres PGPASSWORD=postgres PGUSER_NO_ACCESS=tegola_no_access go test  ./... -v
```
4. `docker compose down`

chore: add docker-compose local dev env

---

provider/postgis/README.md
provider/postgis/error.go
provider/postgis/postgis.go
provider/postgis/postgis_internal_test.go

Hi 👋 
Now with the new pgx it is easier to pass a connection string which was on the wishlist for some issues (eg. #774). If the `uri` is set in the `config.toml` said `uri` is used without compromise as long as the basic information `user`, `password`, `host`, `port` and `database` are set. The `sslmode` is added if not specifically set.
Something on my personal wish list was the addition of  `"max_connection_idle_time"` and `"max_connection_lifetime"` to the config that default to the [pgx default](https://github.com/jackc/pgx/blob/3ce50c079e874c87c4d53eada409738d8504bac6/pgxpool/pool.go#L18) if not specifically set.

feat: allow connection URI and add additional config parameters

---

config/config.go
config/config_test.go
internal/env/parse.go
internal/env/types.go

Using environment variables in `config.Webserver.Headers` would not replace environment variables currently. I therefore added an additional step in `config.Parse` that would iterate over the header and resolve the environment variables if possible. I opted to otherwise raise if the environment variable is not present similar to the behaviour we have right now if any other env is missing. This could also just handle the error and use the original value.
I updated the tests accordingly and added some more to test in isolation. 
As mentioned on slack I'm not sure if that is the correct spot to fix it, so your input is greatly appreciated as usual. :)

fix: replace environment variables in webserver headers

---

atlas/layer.go
atlas/map.go
cmd/internal/register/maps.go
config/config.go
config/config_test.go
maths/validate/validate.go

We have a use case with a very large (85+ GiB, 20+ layers) dataset with small features that only need to be served on one zoom level. "Small" means that the features are usually not bigger than 1 tile in the single zoomlevel that they are served on. The features in the dataset are validated beforehand (self intersecting, etc). Clipping, simplifying and cleaning/validating are not necessary in our case, and disabling them increases performance. Especially cleaning takes a lot of processing time, which takes the response time above a workable threshold for this dataset. (Especially when clipping is disabled, but that's a [known issue](https://github.com/go-spatial/tegola/blob/v0.15.x/atlas/map.go#L290), I believe.)
tl;dr: an option to disable cleaning/making valid

Add a dont_clean option

---

internal/ttools/getenv.go
internal/ttools/getenv_test.go
provider/postgis/postgis_internal_test.go
provider/postgis/util_internal_test.go

More than once I stumble upon this during testing. Previously a local test required to setup the local development environment and passing a bunch of environment variables prior to running `go test ./...`. 
```
docker compose up
RUN_POSTGIS_TESTS=yes \ 
RUN_REDIS_TESTS=yes \ 
PGSSLMODE=disable \ 
PGSSLKEY="" \ 
PGSSLCERT="" \ 
PGSSLROOTCERT="" \
PGHOST=localhost \
PGPORT=5432 \
PGDATABASE=tegola \
PGUSER=postgres \
PGPASSWORD=postgres \
PGUSER_NO_ACCESS=tegola_no_access \
go test  ./... -v
```
Now we allow for environment variables to be passed, but also default back to variables we used across tests and pipelines as default, making testing a little more comfy.
```
RUN_POSTGIS_TESTS=yes \ 
RUN_REDIS_TESTS=yes \ 
go test  ./... -v
```
wdyt?

test: add a ttools helper for easier local testing

---

atlas/map.go
atlas/map_test.go

Prior to this, setting min_zoom=0 and max_zoom=0 would result
in the layer being present across the entire zoom range.
Should fix #870

fix: filter by zoom level for min/max zoom 0

---

config/config.go
config/config_test.go

as per #870, setting max_zoom to 0 currently causes the layer to bleed through
over the entire zoom range. Either we fix filtering as per #871
or make sure max_zoom is never 0 as I do in this PR.

fix: config max zoom 0

---

cmd/tegola/cmd/cache/seed_purge.go
cmd/tegola/cmd/cache/worker.go

This PR adds a `--log-threshold int` command line argument to the `seed` command to limit which tiles produce logs when rendered. Tiles that render in less than `int` milliseconds will not produce logging output. The default value is 0, at which all tiles rendered will be logged.
My goal here is to reduce noise and get a better sense of which zoom levels actually need to be cached (as opposed to rendered on the fly).
Fixes #878

feat: parameter to control tile logging during seeding

---

config/config_test.go
internal/env/dict_test.go
internal/env/types_internal_test.go
internal/ttools/getenv_test.go

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and unsetting the env var) on every instance.
```go
func TestFoo(t *testing.T) {
// before
key := "ENV"
originalEnv := os.Getenv(key)
if err := os.Setenv(key, "new value"); err != nil {
t.Fatal(err)
}
defer func() {
if err := os.Setenv(key, originalEnv); err != nil {
t.Logf("failed to set env %s back to original value: %v", key, err)
}
}()
// after
t.Setenv(key, "new value")
}
```

test: use `T.Setenv` to set env vars in tests

---

internal/build/build.go
provider/hana/hana.go
provider/postgis/postgis.go
server/server.go

we encountered an issue where tegola would panic if you'd try to register duplicate metrics collectors.
that would happen if you have more than one mvt provider in the same config file.
this fix makes provider metrics unique by adding the respective provider name to an array of constant labels. Upon collecting metrics on start up we'd pass unique metrics to the registration step and avoid said panic.
resolves: #886

fix: prometheus with multiple providers

---

.github/workflows/on_pr_push.yml

As per @mrylov comment here: https://github.com/go-spatial/tegola/pull/893\#discussion_r1136602372 the connection string is exposed on purpose. Let's comment for future reference.

chore: comment hana connection string

---

.gitignore
ui/index.html
ui/package-lock.json
ui/package.json
ui/src/App.vue
ui/src/components/LeftNav/LeftNav.vue
ui/src/components/ViewerMapbox.vue
ui/src/globals/store.js
ui/src/main.js
ui/vite.config.js

Hi everyone, this is my 2nd attempt to migrate the internal UI Viewer project.
All the UI (dev) libraries have been updated to the most recent versions.
Mapbox -> MapLibre
Vue2 -> Vue3
Vue Cli -> Vite

MapLibre - Vue3 - Vite Migration v2

---

cache/gcs/gcs.go

This picks up two dropped `err` variables in `cache/gcs`.

fix: cache/gcs dropped errs

---

.github/workflows/on_release_publish.yml

Use docker buildx to build multi-platform images

---

internal/build/build.go
internal/build/viewer.go
ui/embed.go

The compiled UI code naming convention changed at some point and the previous way to parse the version from the file name no longer aligned with the new convention.
closes #942

Fix ui version checking during build

---

provider/hana/hana.go

This fixes a dropped `err` variable in the `provider/hana` package.

provider/hana: fix dropped error

---

.github/actions/tegola-setup-env/action.yml
.github/actions/upload-artifact/action.yml
.github/workflows/on_pr_push.yml
.github/workflows/on_release_publish.yml

In this PR the following changes are made:
* Add `govulncheck` job. This will no run the go team vulnerability scan on every code change and report any issues.
* Upgrade all deprecated actions: Several actions were throwing deprecation warnings due to them using Node.js 16. I updated all actions that were throwing warnings to the newest versions available.

ci: Add govulncheck job. Update actions with deprecation warnings

---

provider/postgis/README.md
provider/postgis/postgis.go
provider/postgis/postgis_test.go
provider/postgis/util_internal_test.go

`application_name` and `default_transaction_read_only` to be configurable
Closes: #966

feat: allow dbconfig options

---

Dockerfile
README.md
go.mod

@gdey this bumps Go up to 1.21.8 to address some of the stdlib vulns. govulncheck is still failing on a few other dependencies that I will update after this one lands.

Bump Go version to 1.21.8

---

.github/workflows/on_pr_push.yml
mvtprovider/postgis/README.md
provider/postgis/README.md
provider/postgis/postgis.go
provider/postgis/postgis_internal_test.go
provider/postgis/postgis_test.go
provider/postgis/util_internal_test.go

refactor: deprecate non uri connection

---

cache/s3/README.md
cache/s3/s3.go

Hi folks!
At Wikimedia we use Tegola on Kubernetes and recently we noticed a performance regression when the internal S3 endpoint changed its TLS certificate (more info https://phabricator.wikimedia.org/T344324). We currently use version 0.19.x, we haven't tested the more recent ones, but we'd like to use a local sidecar/proxy to improve HTTP connection pooling and similar settings.
We are currently connecting from the pod directly to the internal S3 endpoint, and we may explore other alternatives if you don't like the one proposed in this patch. The only one that comes to mind is adding explicit settings to tune HTTP connection pooling and similar in tegola's AWS sdk config for S3.
Technical details:
If Tegola is configured to use a s3 cache endpoint like http://localhost:1234, the AWS …

cache: allow to set a local proxy endpoint for s3

---

atlas/map.go
atlas/map_test.go

refers to #869 
use direct comparison instead of strings.Contains to filter layernames
happy to discuss if we need to support both approaches.

Layer names that are substrings cause atlas to serve all layers that match

---

.github/workflows/on_release_publish.yml

as discussed in #995 docker build should only run if `secrets.DOCKERHUB_USERNAME` and `secrets.DOCKERHUB_TOKEN` are present.

ci: build docker only when secrets are present

---

cache/redis/README.md
cache/redis/redis.go
cache/redis/redis_test.go

feat: allow connection to redis using uri

---

server/handle_map_style_test.go
server/server.go
server/server_internal_test.go
ui/README.md
ui/package-lock.json
ui/package.json

The hostName func is used to dynamically determine the hostName value in various API endpoints. The previous logic favored the Host value of request URL, but this value is often not set (i.e. when not operating behind a proxy). The default handling has been changed to return the request Host value if the request URL Host is not set.
This PR also addresses the outstanding ui vulns.

Enhance server hostName handling

---

ui/src/App.vue
ui/src/components/MapControls.js
ui/src/components/Viewer.vue

After the viewer was migrated from mapboxgl to maplibregl the associated CSS references were not updated. This caused the styling for the inspector to use default browser styles. The style references have now been corrected.
Additionally the debug tile line map control implementation was was using mapboxgl CSS classes so the control was not being added to the map. This has been fix.

ui: Fix inspector CSS. Fix custom map control

---

cmd/tegola/cmd/cache/seed_purge.go

For validating the args for srid-bounds we were using the wrong values. Change from dest values of conversion to supported source values.

The Arg processing for seed/purge for srid-bounds is wrong.

---

maths/triangle.go
observability/observability.go
provider/gpkg/binary_header.go
provider/test/emptycollection/provider.go

fix some function names in comment

chore: fix some function names in comment

---

.github/workflows/on_pr_push.yml

- drops GHA builtin services in favor of docker compose for more flexibility
- also aligns local test environment with gha test environment
Would like to merge this before #1032 @ARolek, to separate it contextually. 😄

ci: use docker compose in gha

---

.github/workflows/on_release_publish.yml

- ci will always fail on branches because docker credentials live upstream
I think the CI is due for an overhaul, as this is just bandage for a bigger misconfiguration. I remember we had to have that default branch logic, because tegola had named default branches that'd change version to version. This is no longer the case, so we could clean that up altogether. 
Might be worth looking into [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and automatic release tagging using [svu](https://github.com/caarlos0/svu) paired with [goreleaser](https://github.com/goreleaser/goreleaser).

ci: dont attempt to publish edge container if credentials are not present
